### PR TITLE
Added SCEW inject bitstrem from Net Yaroze

### PR DESCRIPTION
**Pull request by phatex19**

### CODE REVIEW

**Comment by kalymos** [comment]
Hello.
If it does not bother, I will look with the devloper of the most active branch (rama3), to integrate directly with the most promising code.

**Comment by phatex19** [comment]
Hi,
it's not a problem! :)

P.

Il 08 giu 2017 21:42, "kalymos" <notifications@github.com> ha scritto:

Hello.
If it does not bother, I will look with the devloper of the most active
branch (rama3), to integrate directly with the most promising code.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kalymos/PsNee/pull/1#issuecomment-307206887>, or mute
the thread

**Comment by lucoot** [comment]
Sony Computer Entertainment "Worldwide"?
Which region games use this?

**Comment by stek29** [comment]
@lucoot [it's a devkit](https://en.m.wikipedia.org/wiki/Net_Yaroze)

**Comment by ramapcsx2** [comment]
This PR is outdated. It would be quite hard to test this as well.

**Pull request closed without merging**
